print ("Town name: ")
TownName = input()
print ("Family member: ")
FamilyMember = input()
print ("Describing word: ")
DescribingWord = input()
print ("Action: ")
Action = input()
print ("Thing: ")
Thing = input()
print ("Place: ")
Place = input()

print("One day in ", TownName, " I saw my " , FamilyMember , " acting ", end = "" )
print(DescribingWord , "she was" , Action , " a big " , Thing, end = " ")
print("Then she went to " , Place , " and did it again!")